codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: '70...100'

  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: true
    patch:
      default:
        target: 70%
        threshold: 5%
        informational: true

comment:
  layout: 'reach,diff,flags,files'
  behavior: default
  require_changes: false

ignore:
  - 'crates/*/tests/**'
  - 'crates/*/src/main.rs'
